### ISSUE TITLE
Undo option

### ISSUE THREAD

**Issue by meevm** [vidyamantra/virtualclass#11]
To undo the last action

**Comment by jgupta** [comment]
Undo in editor or in whiteboard or in both?

**Comment by meevm** [comment]
Hi,

Undo in editor code.

In whiteboard active all button can do the needful, provided it selected
the correct object to be actioned, which at present is a problem.

Regards,
Meenakshi Choudhary
Assistant Manager
Vidya Mantra EduSystems Pvt. Ltd.
F-01, Signature Tower,
M/S Ansal IT City & Parks Ltd.
TZ-06, Tech Zone,
Greater Noida,
Uttar Pradesh-201308
Mob No. 9971035577
Google Map : https://goo.gl/FnhkD6 <https://goo.gl/FnhkD6>

**Comment by bogatisuman** [comment]
Performing same way as firpad does.
