### ISSUE TITLE
No instructions added to run this app

### ISSUE THREAD

**Issue by harsh1412** [vidyamantra/virtualclass#259]
I tried to run this application from web hosting.
I couldn't
I tried to run this from node js web hosting but i coudn't
Please create a readme file on how to run this app.

Thanks.

**Comment by jgupta** [comment]
Kindly use following links as examples.

https://github.com/vidyamantra/virtualclass/tree/master/v.vidya.io
https://github.com/vidyamantra/virtualclass/tree/master/example

At present, we are working on doing major updates to this application, once that is done we will bring our focus to documentation. We welcome all pull requests.
