### ISSUE TITLE
Related Videos at end of Video

### ISSUE THREAD

**Issue by nirmala10** [vidyamantra/virtualclass#26]
Once student  youtube video is played completely ,after that if student plays a new video from the available options in youtube. There can be two different videos in student and teacher's screen.
student should be restricted to play a video selected by the teacher.

**Comment by jgupta** [comment]
Teacher can also select a related video which won't be played to students. (Reported by Nirmala at #27 )

We should try to disable related videos completely.

**Comment by jgupta** [comment]
Add rel=0

https://github.com/vidyamantra/virtualclass/blob/master/src/youtube.js#L240
https://developers.google.com/youtube/player_parameters#rel
