### ISSUE TITLE
Remove extra coded css from "styles.css" and "jquery.ui.chatbox.css"

### ISSUE THREAD

**Issue by susmita123** [vidyamantra/virtualclass#4]
Remove extra coded css from "styles.css" and "jquery.ui.chatbox.css" 

for example :  /* border: 2px solid lightgrey;*//* #6699FF */

![screen shot 2015-02-27 at 10 14 39 am](https://cloud.githubusercontent.com/assets/3794936/6407613/e553b468-be69-11e4-83a0-85f1f72343be.png)

**Comment by bogatisuman** [comment]
Now it's done.
