### ISSUE TITLE
In index.php no body,html,title tags please check

### ISSUE THREAD

**Issue by susmita123** [vidyamantra/virtualclass#5]
In example folder index.php has no body,html,title tags please check.

![screen shot 2015-02-27 at 10 35 52 am](https://cloud.githubusercontent.com/assets/3794936/6407749/71f90ea2-be6c-11e4-9916-4d550addc2a0.png)

![screen shot 2015-02-27 at 10 29 09 am](https://cloud.githubusercontent.com/assets/3794936/6407699/8235725c-be6b-11e4-98f5-5a325396424c.png)

**Comment by bogatisuman** [comment]
done
