### ISSUE TITLE
W3c validation error in CSS and HTML please re check all code

### ISSUE THREAD

**Issue by susmita123** [vidyamantra/virtualclass#6]
W3c validation error in CSS and HTML please re check all code.

Copy code from "index.html" and validate into http://validator.w3.org
see error

![screen shot 2015-02-27 at 10 37 15 am](https://cloud.githubusercontent.com/assets/3794936/6407765/ca56f848-be6c-11e4-8c0a-4c62a557310f.png)

**Comment by bogatisuman** [comment]
virtualclass is not compatible with HTML4. we need HTML5 for run virtualclass, how ever will do re-validated the code in HTML5.

**Comment by bogatisuman** [comment]
Has been validate now.
