### ISSUE TITLE
In Firefox view and Chrome view is not same https://d.vidya.io

### ISSUE THREAD

**Issue by susmita123** [vidyamantra/virtualclass#7]
In Firefox view and Chrome view is not same https://d.vidya.io 
Please check this issue. when open same link in both browser.

For example : In Firefox

![screen shot 2015-02-27 at 10 42 48 am](https://cloud.githubusercontent.com/assets/3794936/6407786/771ab592-be6d-11e4-9537-0ead8d3c481e.png)

For example : In Chrome

![screen shot 2015-02-27 at 10 42 34 am](https://cloud.githubusercontent.com/assets/3794936/6407789/84887bce-be6d-11e4-99e5-6b9699d5b6d3.png)

**Comment by bogatisuman** [comment]
You are in different mode(teacher/student) in both browser.

You are logged in as teacher in chrome, on which the toolbar and other settings are enable by default whereas in firefox there is no teacher's control.
