### ISSUE TITLE
Editor status and buttons

### ISSUE THREAD

**Issue by jgupta** [vidyamantra/virtualclass#72]
Enable editor and Disable editor options  appearing at wrong time.- need to clarify  whether the hover description shows the present status or shows the effect after clicking

**Comment by bogatisuman** [comment]
More Info : http://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan

**Comment by bogatisuman** [comment]
We will not provide status, we will provide action.
