### ISSUE TITLE
Whiteboard selected tool doesn't highlights after page refresh.

### ISSUE THREAD

**Issue by ypshukla** [vidyamantra/virtualclass#723]
If any tool selected in whiteboard, it highlights until refresh. After refreshing the page no selection highlighted:
Before refresh:
![screenshot from 2018-07-13 10-38-09](https://user-images.githubusercontent.com/36185596/42673394-e05eecb2-8688-11e8-8fd0-08d232775ae1.png)
After refresh:
![screenshot from 2018-07-13 10-38-30](https://user-images.githubusercontent.com/36185596/42673410-f6ccce56-8688-11e8-8b68-9a072bcec7ed.png)

**Comment by Shubhamvaishala** [comment]
fixed, commit id 'e933e73bc9156ee4e6115588733203b73af33d36'
