### ISSUE TITLE
Whiteboard /Document sharing: Any tool selected (except the triangle) after page refresh selection switch to triangle.

### ISSUE THREAD

**Issue by ypshukla** [vidyamantra/virtualclass#724]
When select any tool (rectangle, straight line, freehand, oval or text box) except the triangle, draw something & refresh the page. After refresh clear all, automatically triangle selected.

**Before refresh:**
![screenshot from 2018-07-13 10-48-05](https://user-images.githubusercontent.com/36185596/42673716-54fd89ce-868a-11e8-9420-c8b477248f22.png)
**Clear all:**
![screenshot from 2018-07-13 10-48-31](https://user-images.githubusercontent.com/36185596/42673723-57f49488-868a-11e8-8725-4164c3606aef.png)

**Triangle selected automatically:**
![screenshot from 2018-07-13 10-48-41](https://user-images.githubusercontent.com/36185596/42673725-59cf0bee-868a-11e8-8b7d-7dd3c0f5721b.png)

**Comment by Shubhamvaishala** [comment]
fixed
