### ISSUE TITLE
Zoom controllers shouldn't display on document dashboard.

### ISSUE THREAD

**Issue by ypshukla** [vidyamantra/virtualclass#725]
When any document selected on document dashboard, the zoom controllers, fit to screen & reload document buttons are visible. It should only display while document sharing.
![screenshot from 2018-07-13 11-05-38](https://user-images.githubusercontent.com/36185596/42674464-753643ae-868d-11e8-8c58-bf10df36352e.png)

**Comment by nirmala10** [comment]
fixed
