### ISSUE TITLE
Document sharing: Finish button disappears.

### ISSUE THREAD

**Issue by ypshukla** [vidyamantra/virtualclass#728]
After sharing the document, if teacher switch to video or presentation and return to document dashboard, the finish button disappears. 
 
**Before switching:**
![screenshot from 2018-07-13 11-33-09](https://user-images.githubusercontent.com/36185596/42675252-d577dd10-8690-11e8-82f1-fa3afe92ac24.png)

**After switch to video or presentation & return to document dashboard:**
![screenshot from 2018-07-13 11-33-24](https://user-images.githubusercontent.com/36185596/42675269-e7947954-8690-11e8-8126-d858a148df5e.png)

**Comment by nirmala10** [comment]
fixed
