### ISSUE TITLE
During document /Video upload if switch to another app, upload progress bar disappears.

### ISSUE THREAD

**Issue by ypshukla** [vidyamantra/virtualclass#732]
During document or video upload if teacher switch to another app & return to document /video dashboard, the upload progress bar disappears.
In this case the document dashboard becomes freezed until the document uploaded successfully in background.
In video upload the progress bar disappears & after a few moments it appears like this & teacher can't track the exact progress of video upload:
![screenshot from 2018-07-13 12-28-23](https://user-images.githubusercontent.com/36185596/42677142-7e5b56da-8698-11e8-8467-7ba55f63343f.png)

**Comment by nirmala10** [comment]
fixed.
