### ISSUE TITLE
Quiz report contains multiple decimal points for max marks and scored marks.

### ISSUE THREAD

**Issue by ypshukla** [vidyamantra/virtualclass#739]
After submit the quiz student gets the report but after refresh another report displayed on the screen which contains multiple decimal points:

![screenshot from 2018-07-13 15-37-34](https://user-images.githubusercontent.com/36185596/42686300-1345444e-86b3-11e8-8895-cf4894322d0a.png)

**Comment by Shubhamvaishala** [comment]
you scored fixed by suman,
maximum mark fixed by shubham
