### ISSUE TITLE
Whiteboard & Document sharing: Clear all one page & refresh, clears the data of all pages.

### ISSUE THREAD

**Issue by ypshukla** [vidyamantra/virtualclass#758]
When teacher draw something on white board or annotate document (document sharing) on various pages & clear all the first page only. After refresh all pages became blank but student side all data still displayed excluding the first page.

**Comment by bogatisuman** [comment]
https://github.com/vidyamantra/virtualclass/commit/8d7026b18a3a02c87013aaa282806d9a0644bc49
